services:
    kafka:
        image: apache/kafka:3.9.0
        container_name: kafka
        ports:
            - "9094:9094"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: >
                INTERNAL_LISTENER://kafka:9092, CONTROLLER://localhost:9093, EXTERNAL_LISTENER://0.0.0.0:9094
            KAFKA_ADVERTISED_LISTENERS: >
                INTERNAL_LISTENER://kafka:9092, EXTERNAL_LISTENER://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
                CONTROLLER:PLAINTEXT, INTERNAL_LISTENER:PLAINTEXT, EXTERNAL_LISTENER:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 3
            CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
        networks:
            - project-net
    flinkjobmanager:
        build: flink_cluster
        container_name: flink_jobmanager
        ports:
            - "8081:8081"
        command: jobmanager
        environment:
            - |
              FLINK_PROPERTIES=
              jobmanager.rpc.address: flinkjobmanager
              parallelism.default: 2
        networks:
            - project-net
    flinktaskmanager:
        build: flink_cluster
        depends_on:
            - flinkjobmanager
        command: taskmanager
        deploy:
            replicas: 3
        environment:
            - |
              FLINK_PROPERTIES=
              jobmanager.rpc.address: flinkjobmanager
              parallelism.default: 2
        networks:
            - project-net
    flinkjob:
        build: consumer_flink
        depends_on:
            - flinkjobmanager
        environment:
            - |
              FLINK_PROPERTIES=
              jobmanager.rpc.address: flinkjobmanager
        networks:
            - project-net
        tty: true
        stdin_open: true
        volumes:
            - ./consumer_flink:/consumer_flink
        command: [ "bash" ]

    postgres:
        image: postgres:16
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: ecommercedb
            POSTGRES_USER: aratae
            POSTGRES_PASSWORD: Dexter121118,
        networks:
            - project-net
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/init:/docker-entrypoint-initdb.d
            - /var/lib/postgresql/data

    simulator:
        build:
            context: ./ecommerce_simulator
        env_file:
            - ./ecommerce_simulator/.env
        container_name: simulator
        depends_on:
            - kafka
        networks:
            - project-net
        command: [ "python", "run_simulator.py" ]
networks:
    project-net:
        driver: bridge
